"""empty message

Revision ID: 0e9927eaf31e
Revises: 83554f26a91d
Create Date: 2021-03-03 18:45:27.399792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9927eaf31e'
down_revision = '83554f26a91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoritos', sa.Column('type_favorito', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favoritos', 'type_favorito')
    # ### end Alembic commands ###
